version: '3.8'

services:
  vscode-server:
    build: .
    # Alternative: use pre-built image from Docker Hub
    # image: ctdgunner/vs-code-server:latest
    
    ports:
      - "8000:8000"  # VS Code Server web interface
      - "2222:22"    # SSH access (mapped to avoid conflicts with host SSH)
    
    volumes:
      # VS Code data persistence (from original ahmadnassri/vscode-server container)
      - ./server-data:/root/.vscode/server-data
      - ./user-data:/root/.vscode/user-data  
      - ./cli-data:/root/.vscode/cli-data
      - ./extensions:/root/.vscode/extensions
      
      # SSH access configuration (added in this extension)
      - ./ssh-keys/authorized_keys:/root/.ssh/authorized_keys:ro
      
      # Optional: Mount your development projects
      - ./projects:/workspace
      
      # Optional: Mount additional configuration files
      - ./config:/root/.config
      
      # Optional: Mount git configuration
      - ./git-config:/root/.gitconfig:ro
      
      # Optional: Mount SSH config and known_hosts
      - ./ssh-keys/config:/root/.ssh/config:ro
      - ./ssh-keys/known_hosts:/root/.ssh/known_hosts:ro
    
    environment:
      # Set default shell
      - SHELL=/bin/bash
      
      # Optional: Set timezone
      - TZ=UTC
      
      # Optional: Git configuration (alternatively mount .gitconfig)
      # - GIT_AUTHOR_NAME=Your Name
      # - GIT_AUTHOR_EMAIL=your.email@example.com
      # - GIT_COMMITTER_NAME=Your Name  
      # - GIT_COMMITTER_EMAIL=your.email@example.com
    
    restart: unless-stopped
    
    container_name: vscode-dev-server
    
    # Optional: Add hostname for easier identification
    hostname: vscode-dev-server
    
    # Optional: Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '1.0'
    #     reservations:
    #       memory: 512M
    #       cpus: '0.5'

# Optional: Create a dedicated network
# networks:
#   vscode-dev:
#     driver: bridge

# Optional: Define named volumes instead of bind mounts
# volumes:
#   vscode-server-data:
#   vscode-user-data:
#   vscode-cli-data:
#   vscode-extensions: