version: '3.8'

services:
  vs-code-server:
    image: ctdgunner/vs-code-server:latest
    
    ports:
      - "8000:8000"  # VS Code Server web interface
      - "2222:22"    # SSH access (mapped to avoid conflicts with host SSH)
    
    volumes:
      # Projects Directory
      - ./projects/:/projects/
      
      # VS Code App Data  
      - ./vs-code-server/:/root/
    
    environment:
      # Set default shell
      - SHELL=/bin/bash
      
      # Timezone
      - TZ=UTC
      
      # Git configuration via environment variables
      - GIT_USER_NAME=
      - GIT_USER_EMAIL=
    
    restart: unless-stopped
    
    container_name: vs-code-server
    
    # Add hostname for easier identification
    hostname: vscode