name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Check for base image updates daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-base-image:
    runs-on: ubuntu-latest
    outputs:
      base-updated: ${{ steps.check.outputs.updated }}
    steps:
      - name: Check if base image was updated
        id: check
        run: |
          # Get the current digest of the base image
          CURRENT_DIGEST=$(docker manifest inspect ahmadnassri/vscode-server:latest | jq -r '.manifests[0].digest')
          
          # Try to get the previously stored digest
          PREVIOUS_DIGEST="${{ vars.BASE_IMAGE_DIGEST || 'none' }}"
          
          if [ "$CURRENT_DIGEST" != "$PREVIOUS_DIGEST" ]; then
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "Base image updated from $PREVIOUS_DIGEST to $CURRENT_DIGEST"
          else
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "Base image unchanged: $CURRENT_DIGEST"
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-base-image
    if: github.event_name != 'schedule' || needs.check-base-image.outputs.base-updated == 'true'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update base image digest
        if: needs.check-base-image.outputs.base-updated == 'true'
        run: |
          CURRENT_DIGEST=$(docker manifest inspect ahmadnassri/vscode-server:latest | jq -r '.manifests[0].digest')
          echo "BASE_IMAGE_DIGEST=$CURRENT_DIGEST" >> $GITHUB_ENV
          # Note: You'll need to manually update the repository variable BASE_IMAGE_DIGEST
          # or use a GitHub App token with appropriate permissions